name: Release

on:
  workflow_dispatch:
  pull_request:
    branches: [master, dev]
    types: [opened, synchronize, reopened]
  push:
    branches: [master, dev]
    paths-ignore:
      - '**.md'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: false

      - name: Build
        run: make all

      - name: Create Release and Upload Assets
        uses: akkuman/gitea-release-action@v1
        with:
          token: ${{ secrets.GITEA_TOKEN }}
          server_url: ${{ gitea.server_url }}
          files: |
            bin/*
          name: Release ${{ github.ref_name }}
          body: "Automated release for ${{ github.ref_name }}"
